services:
  frontend:
    build: frontend
    ports:
      - 4200:80
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - spring-mysql
    depends_on:
      - database
  database:
    build: database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
volumes:
  db-data:
networks:
  spring-mysql:
