name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create init.sql from secret
        run: echo "${{ secrets.INIT_SQL }}" > database/init.sql

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dlbsepdocd01-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dlbsepdocd01-backend:latest

      - name: Build and push database image
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dlbsepdocd01-database:latest